"""create_all_tables

Revision ID: 55d82ac28783
Revises:
Create Date: 2026-07-04 23:31:15.153556

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55d82ac28783"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_history",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "login_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("logout_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("full_name", sa.String(length=64), nullable=False),
        sa.Column("date_born", sa.Date(), nullable=False),
        sa.Column(
            "gender", sa.Enum("MALE", "FEMALE", "NOT_SAY", name="gendertype"), nullable=False
        ),
        sa.Column("cpf", sa.String(length=15), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "banks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("agency", sa.String(length=32), nullable=False),
        sa.Column("account_number", sa.String(length=32), nullable=False),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cashes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("installments", sa.Integer(), nullable=False),
        sa.Column("installs_paid", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column(
            "invoice_type",
            sa.Enum(
                "CASH",
                "PIX",
                "DOC",
                "TED",
                "CREDIT_CARD",
                "DEBIT_CARD",
                "CHECK",
                "BANK_SLIP",
                "OTHER",
                name="invoicetype",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", "CANCELED", "CONTINUED", name="invoicestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "money_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("bank_id", sa.UUID(), nullable=True),
        sa.Column("bank_box_id", sa.UUID(), nullable=True),
        sa.Column("cash_id", sa.UUID(), nullable=True),
        sa.Column("invoice_id", sa.UUID(), nullable=True),
        sa.Column(
            "type_opp",
            sa.Enum("PAYMENT", "RECEIPT", "TRANSFER", name="moneytype"),
            nullable=False,
        ),
        sa.Column(
            "method_opp",
            sa.Enum(
                "CASH",
                "PIX",
                "DOC",
                "TED",
                "CREDIT_CARD",
                "DEBIT_CARD",
                "CHECK",
                "BANK_SLIP",
                "OTHER",
                name="moneymethod",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "salary",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("company", sa.String(length=64), nullable=True),
        sa.Column("occupation", sa.String(length=64), nullable=True),
        sa.Column("salary", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("activated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bank_boxes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bank_id", sa.UUID(), nullable=False),
        sa.Column("tag", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("balance", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["banks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pixes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bank_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column(
            "pix_type",
            sa.Enum("CPF", "CNPJ", "EMAIL", "PHONE", "RANDOM", name="pixtype"),
            nullable=False,
        ),
        sa.Column("is_mine", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bank_id"],
            ["banks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pixes")
    op.drop_table("bank_boxes")
    op.drop_table("salary")
    op.drop_table("money_logs")
    op.drop_table("invoices")
    op.drop_table("cashes")
    op.drop_table("banks")
    op.drop_table("users")
    op.drop_table("login_history")
    # drop types enums
    op.execute("DROP TYPE IF EXISTS gendertype CASCADE")
    op.execute("DROP TYPE IF EXISTS invoicetype CASCADE")
    op.execute("DROP TYPE IF EXISTS invoicestatus CASCADE")
    op.execute("DROP TYPE IF EXISTS moneytype CASCADE")
    op.execute("DROP TYPE IF EXISTS moneymethod CASCADE")
    op.execute("DROP TYPE IF EXISTS pixtype CASCADE")
    # ### end Alembic commands ###
